q1 = input("what is the bigest contry?:")
q2 = input("what is 59 + 41?:")
q3 = input("what is the capital of france?: A london. B paris. D new york :")
q4 = input("how many republics did the u.s.s.r have?: A 900. B 78. C 0. D 15. E 34: ")
fq = input("how many present is my phone batry?: A 51. B 96")
print(q1)
print(q2)
print(q3)
print(q4)
print(fq)
for i in range(1,10 + 1):
    print("good job")